import type { Session } from '@supabase/supabase-js';
import { useCallback, useEffect, useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { FormInput } from '../components/FormInput'; import { PrimaryButton } from '../components/PrimaryButton'; import { supabase } from '../lib/supabase'; import { colors } from '../theme'; import type { TouringGroup } from '../types';
type Props = { session: Session; onOpenGroup: (group: TouringGroup) => void };
export function GroupsScreen({ session, onOpenGroup }: Props) {
  const [groups, setGroups] = useState<TouringGroup[]>([]); const [groupName, setGroupName] = useState(''); const [inviteCode, setInviteCode] = useState(''); const [loading, setLoading] = useState(false); const [refreshing, setRefreshing] = useState(false); const [message, setMessage] = useState('');
  const loadGroups = useCallback(async () => { if (!supabase) return; const { data, error } = await supabase.from('group_members').select('touring_groups(*)').eq('user_id', session.user.id); if (error) setMessage(error.message); else setGroups((data ?? []).map((row: any) => row.touring_groups).filter(Boolean)); }, [session.user.id]);
  useEffect(() => { loadGroups(); }, [loadGroups]);
  async function createGroup() { if (!supabase || !groupName.trim()) return; setLoading(true); setMessage(''); const { data, error } = await supabase.from('touring_groups').insert({ name: groupName.trim(), owner_id: session.user.id }).select().single(); setLoading(false); if (error) setMessage(error.message); else { setGroupName(''); await loadGroups(); onOpenGroup(data as TouringGroup); } }
  async function joinGroup() { if (!supabase || !inviteCode.trim()) return; setLoading(true); setMessage(''); const { data, error } = await supabase.rpc('join_touring_group', { code: inviteCode.trim().toUpperCase() }); setLoading(false); if (error) setMessage(error.message); else { setInviteCode(''); await loadGroups(); onOpenGroup(data as TouringGroup); } }
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async () => { setRefreshing(true); await loadGroups(); setRefreshing(false); }} />}><View style={styles.header}><View><Text style={styles.eyebrow}>MOMOTORAN</Text><Text style={styles.title}>Mau jalan ke mana?</Text></View><PrimaryButton label="Keluar" variant="quiet" onPress={() => supabase?.auth.signOut()} /></View><View style={styles.panel}><Text style={styles.panelTitle}>Bikin rombongan baru</Text><FormInput label="Nama touring" placeholder="Naringgul Minggu Pagi" value={groupName} onChangeText={setGroupName} /><PrimaryButton label="Buat grup" onPress={createGroup} loading={loading} disabled={!groupName.trim()} /></View><View style={styles.panel}><Text style={styles.panelTitle}>Punya kode undangan?</Text><FormInput label="Kode grup" placeholder="Contoh: K7M2PQ" value={inviteCode} onChangeText={setInviteCode} autoCapitalize="characters" maxLength={6} /><PrimaryButton label="Gabung grup" variant="secondary" onPress={joinGroup} loading={loading} disabled={inviteCode.trim().length < 6} /></View>{message ? <Text style={styles.message}>{message}</Text> : null}<View style={styles.list}><Text style={styles.sectionTitle}>Rombongan saya</Text>{groups.length === 0 ? <Text style={styles.empty}>Belum ada grup. Buat grup baru atau masukkan kode temanmu.</Text> : groups.map((group) => <View key={group.id} style={styles.groupCard}><View style={styles.groupInfo}><Text style={styles.groupName}>{group.name}</Text><Text style={styles.groupMeta}>Kode {group.invite_code} · {group.status === 'active' ? 'Sedang jalan' : 'Menunggu'}</Text></View><PrimaryButton label="Buka" variant="secondary" onPress={() => onOpenGroup(group)} /></View>)}</View></ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.sand }, content: { padding: 20, paddingTop: 58, paddingBottom: 48, gap: 18 }, header: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 8 }, eyebrow: { color: colors.orange, fontWeight: '900', fontSize: 12, letterSpacing: 2 }, title: { color: colors.ink, fontWeight: '900', fontSize: 29, marginTop: 7, letterSpacing: -0.7 }, panel: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.line, padding: 18, gap: 14 }, panelTitle: { color: colors.ink, fontSize: 18, fontWeight: '800' }, message: { color: colors.danger, fontSize: 14 }, list: { marginTop: 10, gap: 12 }, sectionTitle: { color: colors.ink, fontSize: 20, fontWeight: '900' }, empty: { color: colors.muted, fontSize: 15, lineHeight: 22, paddingVertical: 14 }, groupCard: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.line }, groupInfo: { flex: 1 }, groupName: { color: colors.ink, fontSize: 17, fontWeight: '800' }, groupMeta: { color: colors.muted, fontSize: 13, marginTop: 5 } });
