import * as Location from 'expo-location';
import { useEffect, useRef, useState } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import MapView, { Marker, PROVIDER_GOOGLE, Region } from 'react-native-maps';
import { PrimaryButton } from '../components/PrimaryButton'; import { supabase } from '../lib/supabase'; import { colors } from '../theme'; import type { LiveLocation, TouringGroup } from '../types';
type Props = { group: TouringGroup; userId: string; onBack: () => void };
const fallbackRegion: Region = { latitude: -6.9175, longitude: 107.6191, latitudeDelta: 0.08, longitudeDelta: 0.08 };
export function TourScreen({ group, userId, onBack }: Props) {
  const [locations, setLocations] = useState<Record<string, LiveLocation>>({}); const [sharing, setSharing] = useState(false); const [message, setMessage] = useState(''); const watcher = useRef<Location.LocationSubscription | null>(null); const map = useRef<MapView | null>(null);
  useEffect(() => { if (!supabase) return; const client = supabase; client.from('live_locations').select('*').eq('group_id', group.id).then(({ data }) => { const next: Record<string, LiveLocation> = {}; for (const item of (data ?? []) as LiveLocation[]) next[item.user_id] = item; setLocations(next); }); const channel = client.channel(`tour:${group.id}`).on('postgres_changes', { event: '*', schema: 'public', table: 'live_locations', filter: `group_id=eq.${group.id}` }, (payload) => { const next = payload.new as LiveLocation; if (next?.user_id) setLocations((current) => ({ ...current, [next.user_id]: next })); }).subscribe(); return () => { watcher.current?.remove(); client.removeChannel(channel); }; }, [group.id]);
  async function startSharing() { if (!supabase) return; const client = supabase; const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') { setMessage('Izin lokasi diperlukan agar anggota grup bisa melihat posisimu.'); return; } setMessage(''); watcher.current = await Location.watchPositionAsync({ accuracy: Location.Accuracy.High, timeInterval: 8000, distanceInterval: 20 }, async ({ coords }) => { const location: LiveLocation = { group_id: group.id, user_id: userId, latitude: coords.latitude, longitude: coords.longitude, accuracy: coords.accuracy, speed: coords.speed, heading: coords.heading, updated_at: new Date().toISOString() }; setLocations((current) => ({ ...current, [userId]: location })); await client.from('live_locations').upsert(location, { onConflict: 'group_id,user_id' }); map.current?.animateToRegion({ latitude: coords.latitude, longitude: coords.longitude, latitudeDelta: 0.025, longitudeDelta: 0.025 }); }); setSharing(true); }
  function stopSharing() { watcher.current?.remove(); watcher.current = null; setSharing(false); }
  const members = Object.values(locations);
  return <View style={styles.page}><MapView ref={map} style={StyleSheet.absoluteFill} provider={Platform.OS === 'android' ? PROVIDER_GOOGLE : undefined} initialRegion={fallbackRegion} showsUserLocation={sharing}>{members.map((member) => <Marker key={member.user_id} coordinate={{ latitude: member.latitude, longitude: member.longitude }} title={member.user_id === userId ? 'Kamu' : member.display_name ?? 'Anggota'} description={`Diperbarui ${new Date(member.updated_at).toLocaleTimeString('id-ID')}`} pinColor={member.user_id === userId ? colors.orange : colors.green} />)}</MapView><View style={styles.topBar}><PrimaryButton label="Kembali" variant="secondary" onPress={onBack} /><View style={styles.groupLabel}><Text numberOfLines={1} style={styles.groupName}>{group.name}</Text><Text style={styles.groupMeta}>{members.length} posisi · Kode {group.invite_code}</Text></View></View><View style={styles.bottomPanel}><View style={styles.statusRow}><View style={[styles.dot, sharing && styles.dotActive]} /><Text style={styles.status}>{sharing ? 'Lokasimu sedang dibagikan' : 'Lokasimu belum dibagikan'}</Text></View>{message ? <Text style={styles.message}>{message}</Text> : null}<PrimaryButton label={sharing ? 'Berhenti bagikan lokasi' : 'Mulai bagikan lokasi'} variant={sharing ? 'secondary' : 'primary'} onPress={sharing ? stopSharing : startSharing} /><Text style={styles.note}>Untuk tahap awal, lokasi aktif selama aplikasi terbuka. Mode background akan ditambahkan lewat development build.</Text></View></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.sand }, topBar: { position: 'absolute', top: 48, left: 16, right: 16, flexDirection: 'row', gap: 10, alignItems: 'center' }, groupLabel: { flex: 1, backgroundColor: colors.surface, borderRadius: 14, paddingHorizontal: 15, paddingVertical: 11, borderWidth: 1, borderColor: colors.line }, groupName: { color: colors.ink, fontSize: 16, fontWeight: '800' }, groupMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, bottomPanel: { position: 'absolute', left: 14, right: 14, bottom: 20, backgroundColor: colors.surface, borderRadius: 20, borderWidth: 1, borderColor: colors.line, padding: 18, gap: 12 }, statusRow: { flexDirection: 'row', alignItems: 'center', gap: 9 }, dot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.line }, dotActive: { backgroundColor: colors.green }, status: { color: colors.ink, fontSize: 15, fontWeight: '800' }, message: { color: colors.danger, fontSize: 13, lineHeight: 19 }, note: { color: colors.muted, fontSize: 12, lineHeight: 17 } });
